Sergiodev: update navbar
i-am-sergio/react-web-epcc pull request #12
Opened 2023-09-16 16:08 UTC by i-am-sergio

2023-09-16 16:27 UTC, 35P10 requested changes
Los links te mandan a una seccion, asi:
![image](https://github.com/i-am-sergio/react-web-epcc/assets/52789278/1e83135b-e3da-469f-b49a-37eb46b3b240)
Pero lo ideal es que se muestre el titulo tambien:
![image](https://github.com/i-am-sergio/react-web-epcc/assets/52789278/db881d1d-1c0d-4e03-bc69-3a25f347b39b)

2023-09-16 16:27 UTC, 35P10 commented on src/css/navbar2.css
>  @import url("https://fonts.googleapis.com/css2?family=Titillium+Web:wght@300;400;700&display=swap");
si no se esta usando el import, quitalo.

2023-09-16 16:27 UTC, 35P10 commented on src/components/Navbar2.jsx
No existe la sección Organizacion.

2023-09-16 16:32 UTC, 35P10 commented on src/css/navbar2.css
>  @import url("https://fonts.googleapis.com/css2?family=Titillium+Web:wght@300;400;700&display=swap");
Tambien reduce el tamaño de la fuente del navbar.

2023-09-16 17:01 UTC, 35P10 commented on src/components/Navbar2.jsx
Solo deben estar las secciones: Inicio, Sobre, Actividades y Ubicación.

2023-09-16 17:01 UTC, 35P10 commented on src/index.css
La solución no debería ser agregarle un padding.

2023-09-16 17:06 UTC, 35P10 commented
No tienes por qué crear otro PR cuando corrijas los cambios, con solo corregirlos en tu rama ya estaría 👌. Mas bien, las observaciones corregidas márcales como resueltas en esta conversion.

2023-09-17 00:03 UTC, 35P10 requested changes
Quita el padding. Busca otra manera de resolver el requerimiento.

2023-09-17 00:03 UTC, 35P10 commented on src/index.css
Sigue el error del padding. 
![image](https://github.com/i-am-sergio/react-web-epcc/assets/52789278/4aeb70b4-40bb-4d88-b881-51a9ce4614fa)

2023-09-17 00:03 UTC, 35P10 commented on src/index.css
![image](https://github.com/i-am-sergio/react-web-epcc/assets/52789278/6f6a1103-7fb8-48fb-87c8-d197a95fd99c)

2023-09-17 21:33 UTC, i-am-sergio commented on src/index.css
no veo el problema ni en diseño ni en funcionamiento con el padding

2023-09-17 22:47 UTC, 35P10 commented on src/index.css
Hola, en el diseño si hay problema: mira cuanto espacio esta ocupando el padding: 
![image](https://github.com/i-am-sergio/react-web-epcc/assets/52789278/dae342ca-bd06-49e6-b663-d5ead0fa60be)
Busca otra alternativa, (aqui hay soluciones que pueden interesarte: https://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header). 
Ademas, en el responsive se manejan, o deberian manejarse diferentes padding. 
Yo te propongo una solucion basada en este articulo https://css-tricks.com/hash-tag-links-padding/:
En cada seccion vas a los estilos del contenedor principal (SASS) y le pones scroll-margin-top: 24px en caso de version movil y en sus breakpoint le cambias ese valor a otro, guíate de estos valores:
![image](https://github.com/i-am-sergio/react-web-epcc/assets/52789278/3601d49e-719f-499a-815b-fa139e87737a)
De hecho, tienes que usar esas variables como tal (se encuentran en el file src\styles\Utils\_layouts.scss), nada de poner valores especificos.

2023-09-18 00:07 UTC, i-am-sergio commented on src/index.css
hola, ese espacio no lo puse yo, y no es por los paddings que agregue, aunque igual use otra solucion sin los padding de acuerdo a lo que me recomendaste

2023-09-18 00:12 UTC, 35P10 requested changes

2023-09-18 00:12 UTC, 35P10 commented on src/index.css
ese espacio es justo por el padding-top: 100px. Bro, checkate la observacion anterior de los breakpoint. esta bien lo del scroll-margin-top, pero hay que ponerlos de acuerdo a los breakpoints.

2023-09-18 00:34 UTC, i-am-sergio commented on src/index.css
los padding que agregue no afectan ese componente(Hero.jsx), yo lo habia agregado para mejorar esto en la secciones de abajo porque estaban muy juntas a mi parecer
![image](https://github.com/i-am-sergio/react-web-epcc/assets/113309955/e1e046c7-6175-49c5-a0be-8b3922d2658b)

el scroll-margin-top solo debe mantener un solo valor por que el navbar nunca aumenta de tamaño en

2023-09-18 00:39 UTC, 35P10 commented on src/index.css
Ahh tienes razon lo del padding, xd sorry, ya lo corregi pero en tu rama no estaba ese cambio.

2023-09-18 00:43 UTC, 35P10 commented on src/index.css
Bueno, sorry por eso, my bad. Esta OK todo. Buen trabajo. 👌

2023-09-18 00:44 UTC, 35P10 commented
Nice. 👌

2023-09-18 00:44 UTC, merged