Update Footer and Stats
i-am-sergio/react-web-epcc pull request #14
Opened 2023-09-17 00:16 UTC by ShinjiMC

2023-09-17 00:53 UTC, 35P10 requested changes
Corrige los cambios y marca como resueltas las observaciones. 👌

2023-09-17 00:53 UTC, 35P10 commented on src/styles/stats.module.scss
Error en responsive:
Mobile:
Las letras estan muy pequeñas, distribuye los 4 stats en 2 por fila.
![image](https://github.com/i-am-sergio/react-web-epcc/assets/52789278/ef8e535a-42b0-4afc-bbe3-d2d7f8d50716)

2023-09-17 00:53 UTC, 35P10 commented on src/styles/stats.module.scss
Vista Mobile:
En la resolución 425px se desarma.
![image](https://github.com/i-am-sergio/react-web-epcc/assets/52789278/29232e22-bf47-488d-84c6-186cac08e8a4)

2023-09-17 00:53 UTC, 35P10 commented on src/styles/stats.module.scss
Vista mobile:
Quitale el margin y agrégale padding de 24px en el eje Y (padding top y bot).
![image](https://github.com/i-am-sergio/react-web-epcc/assets/52789278/ffc1bafd-9f04-4128-baae-c6e32e67538b)
EDIT, estas usando SASS, por lo que puedes solo quitar el margin. y agregarle en los querymedia el mixin `@include section(TUBREAKPOINT);` y no olvides de importar: `@import "./Utils/constants.scss";
@import "./Utils/_layouts.scss";` Revisa los files `src\styles\about.module.scss` y `src\styles\template.module.scss` como guia.

2023-09-17 00:53 UTC, 35P10 commented on src/components/Footer.jsx
por el momento solo deja visible esta seccion:
![image](https://github.com/i-am-sergio/react-web-epcc/assets/52789278/bc4b65b6-d47b-42ad-8aca-4e641de242a7)
Pero conserva la lógica del componente para agregar mas adelante los links.

2023-09-17 01:55 UTC, 35P10 requested changes

2023-09-17 01:55 UTC, 35P10 commented on src/styles/stats.module.scss
La seccion de stats tiene un fondo:
![image](https://github.com/i-am-sergio/react-web-epcc/assets/52789278/cd73728a-a3e4-49d0-8f96-737686d3fa87)

2023-09-17 22:44 UTC, genrommel commented on src/styles/stats.module.scss
> Vista mobile: Quitale el margin y agrégale padding de 24px en el eje Y (padding top y bot). ![image](https://user-images.githubusercontent.com/52789278/268476737-ffc1bafd-9f04-4128-baae-c6e32e67538b.png) EDIT, estas usando SASS, por lo que puedes solo quitar el margin. y agregarle en los querymedia el mixin `@include section(TUBREAKPOINT);` y no olvides de importar: `@import "./Utils/constants.scss"; @import "./Utils/_layouts.scss";` Revisa los files `src\styles\about.module.scss` y `src\styles\template.module.scss` como guia.

FALTA

2023-09-17 22:45 UTC, genrommel commented on src/styles/stats.module.scss
> Error en responsive: Mobile: Las letras estan muy pequeñas, distribuye los 4 stats en 2 por fila. ![image](https://user-images.githubusercontent.com/52789278/268476591-ef8e535a-42b0-4afc-bbe3-d2d7f8d50716.png)



> Vista Mobile: En la resolución 425px se desarma. ![image](https://user-images.githubusercontent.com/52789278/268476654-29232e22-bf47-488d-84c6-186cac08e8a4.png)

RESUELTO

2023-09-17 22:45 UTC, genrommel commented on src/components/Footer.jsx
Se mantiene aún.

2023-09-17 23:04 UTC, genrommel commented on src/styles/stats.module.scss
> Error en responsive: Mobile: Las letras estan muy pequeñas, distribuye los 4 stats en 2 por fila. ![image](https://user-images.githubusercontent.com/52789278/268476591-ef8e535a-42b0-4afc-bbe3-d2d7f8d50716.png)

2023-09-17 23:04 UTC, genrommel commented on src/styles/stats.module.scss
> > Vista mobile: Quitale el margin y agrégale padding de 24px en el eje Y (padding top y bot). ![image](https://user-images.githubusercontent.com/52789278/268476737-ffc1bafd-9f04-4128-baae-c6e32e67538b.png) EDIT, estas usando SASS, por lo que puedes solo quitar el margin. y agregarle en los querymedia el mixin `@include section(TUBREAKPOINT);` y no olvides de importar: `@import "./Utils/constants.scss"; @import "./Utils/_layouts.scss";` Revisa los files `src\styles\about.module.scss` y `src\styles\template.module.scss` como guia.
>

2023-09-17 23:05 UTC, genrommel commented on src/styles/stats.module.scss
> > Error en responsive: Mobile: Las letras estan muy pequeñas, distribuye los 4 stats en 2 por fila. ![image](https://user-images.githubusercontent.com/52789278/268476591-ef8e535a-42b0-4afc-bbe3-d2d7f8d50716.png)
> 
> > Vista Mobile: En la resolución 425px se desarma. ![image](https://user-images.githubusercontent.com/52789278/268476654-29232e22-bf47-488d-84c6-186cac08e8a4.png)
>

2023-09-17 23:05 UTC, genrommel commented on src/styles/stats.module.scss
> > Error en responsive: Mobile: Las letras estan muy pequeñas, distribuye los 4 stats en 2 por fila. ![image](https://user-images.githubusercontent.com/52789278/268476591-ef8e535a-42b0-4afc-bbe3-d2d7f8d50716.png)
> 
> > Vista Mobile: En la resolución 425px se desarma. ![image](https://user-images.githubusercontent.com/52789278/268476654-29232e22-bf47-488d-84c6-186cac08e8a4.png)
>

2023-09-17 23:07 UTC, genrommel commented on src/styles/stats.module.scss
> Error en responsive: Mobile: Las letras estan muy pequeñas, distribuye los 4 stats en 2 por fila. ![image](https://user-images.githubusercontent.com/52789278/268476591-ef8e535a-42b0-4afc-bbe3-d2d7f8d50716.png)

![image](https://github.com/i-am-sergio/react-web-epcc/assets/62628531/55685bdd-d962-4878-ab82-d5382a06b26a)
Falta aplicación del fondo

2023-09-18 04:15 UTC, ShinjiMC commented on src/components/Footer.jsx
Ya lo deje comentado para que luego se descomente y se integre todo
![image](https://github.com/i-am-sergio/react-web-epcc/assets/87953250/f5733b56-7a90-4852-b6fd-200a7b03480f)

2023-09-18 04:19 UTC, ShinjiMC commented on src/styles/stats.module.scss
Ya le modifique para un fondo mas resaltante que el fondo normal, lo modifique para que en las multiples vistas se mantenga el formato de 2x2 o 4x1 y en el padding le puse dos casos uno de 0.375 rem y 1 rem
![image](https://github.com/i-am-sergio/react-web-epcc/assets/87953250/5e7ed6ee-30ed-4b69-a28b-88da7aba3bbb)

2023-09-19 17:56 UTC, 35P10 requested changes
Buen trabajo con el Footer. Revisa las observaciones en Stats. 👌

2023-09-19 17:56 UTC, 35P10 commented on src/styles/stats.module.scss
Estilo:
![image](https://github.com/i-am-sergio/react-web-epcc/assets/52789278/c49a9c93-b259-4075-9a53-867b314af6c4)
- El fondo de color extraelo de la variable "seccion oscuro"
![image](https://github.com/i-am-sergio/react-web-epcc/assets/52789278/ace31838-848e-4555-951b-950d7d1763d0)
- No tiene que tener redondeada las esquinas.

2023-09-19 17:56 UTC, 35P10 commented on src/styles/stats.module.scss
Te recomiendo que coloques los estilos en el orden : mobile, tablet, laptop, ... comenzando desde la pantalla más pequeña:

```
.container_stats {
     vista mobile
}

@media (min-width: map-get($breakpoints, tablet)) {
  .container_stats {
      vista tablet
}
@media (min-width: map-get($breakpoints, laptop)) {
  .container_stats {
      vista laptop
       }

}

```

No es necesario que modifiques el file, pero en el futuro te ayudará a definir los estilos fácilmente. 😊

2023-09-19 17:56 UTC, 35P10 commented on src/styles/stats.module.scss
> +  padding: 0.375rem 0.375rem 0.375rem 0.375rem;
se esta trabajando con paddings predefiindos, por lo que reemplaza el padding por `@include section('TUBREAKPOINT);`

2023-09-19 17:56 UTC, 35P10 commented on src/styles/stats.module.scss
> +      gap: calc(15% - 1rem);
@include section('mobile');

2023-09-19 17:56 UTC, 35P10 commented on src/styles/stats.module.scss
> +      gap: 5rem;
@include section('tablet');

2023-09-19 17:56 UTC, 35P10 commented on src/styles/stats.module.scss
> +      padding: 1rem 1rem 1rem 1rem;
@include section('laptop');

2023-09-25 04:23 UTC, ShinjiMC commented on src/styles/stats.module.scss
Ya le coloque el color desde cnstants
![image](https://github.com/i-am-sergio/react-web-epcc/assets/87953250/b4e21854-b882-4fc9-b9c1-f1bcc5bad161)

2023-09-25 04:24 UTC, ShinjiMC commented on src/styles/stats.module.scss
> +  padding: 0.375rem 0.375rem 0.375rem 0.375rem;
```
align-items: center;
  text-align: center;
  @include section("wide");
```

Ya lo integre

2023-09-25 04:25 UTC, ShinjiMC commented on src/styles/stats.module.scss
> +      gap: calc(15% - 1rem);
```
flex-direction: row;
      gap: calc(15% - 1rem);
      @include section("mobile");
```

En mobile

2023-09-25 04:25 UTC, ShinjiMC commented on src/styles/stats.module.scss
> +      gap: 5rem;
```
      flex-direction: row;
      gap: 5rem;
      @include section("tablet");
```

en vista tablet solucionado

2023-09-25 04:26 UTC, ShinjiMC commented on src/styles/stats.module.scss
> +      padding: 1rem 1rem 1rem 1rem;
```
      justify-content: center;
      gap: 12rem;
      @include section("laptop");
```
Y en vista laptop solucionado

2023-09-29 23:25 UTC, 35P10 commented
Buen trabajo.

2023-09-29 23:25 UTC, merged